package com.vbsoft.Modeles.In.Enums;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Справочник 'Код упаковоки'.
 * Справочник 27 в документе CELLO_EDI Code.
 *
 * @author vd.zinovev
 * @version 1.0
 * @since 1.0
 */
public enum PackingQuantityCode {
    
@JsonProperty("%")
Percentage,
@JsonProperty("%O")
Permille,
@JsonProperty("22S")
SquareMillimeterPerSecond,
@JsonProperty("A")
Ampere,
@JsonProperty("ACR")
Acre,
@JsonProperty("BAG")
Bag,
@JsonProperty("BAR")
Bar,
@JsonProperty("BOX")
BOX,
@JsonProperty("BQK")
BecquerelPerKilogram,
@JsonProperty("BT")
Bottle,
@JsonProperty("BYT")
Bytes,
@JsonProperty("C3S")
CubicCentimeterPerSecond,
@JsonProperty("CAN")
Canister,
@JsonProperty("CC")
CubicCentimeterCIS,
@JsonProperty("CCM")
CubicCentimeter,
@JsonProperty("CD")
Candelas,
@JsonProperty("CF")
CubicFootCIS,
@JsonProperty("CM")
Centimeter,
@JsonProperty("CM2")
SquareCentimeter,
@JsonProperty("CMH")
CentimeterPerHour,
@JsonProperty("CR")
Crate,
@JsonProperty("DEG")
Degree,
@JsonProperty("DM")
Decimeter,
@JsonProperty("DR")
Drum,
@JsonProperty("DZ")
Dozen,
@JsonProperty("EA")
Each,
@JsonProperty("EML")
EnzymeUnitsPerMilliliter,
@JsonProperty("F")
Farad,
@JsonProperty("FT")
Foot,
@JsonProperty("FT2")
SquareFoot,
@JsonProperty("FT3")
CubicFoot,
@JsonProperty("G")
Gram,
@JsonProperty("GPerL")
GrammarIngridPearlier,
@JsonProperty("GA")
GallonCIS,
@JsonProperty("GAU")
GramGold,
@JsonProperty("GHG")
GramPerHectogram,
@JsonProperty("GJ")
GigaJoule,
@JsonProperty("GKG")
GramPerKilogram,
@JsonProperty("GLI")
GramPerLiter,
@JsonProperty("GM")
GramPerMol,
@JsonProperty("GM2")
GramPerSquareMeter,
@JsonProperty("GPH")
GallonsPerHourUS,
@JsonProperty("GRO")
Gross,
@JsonProperty("GT")
GITA,
@JsonProperty("H")
Hour,
@JsonProperty("HL")
HectoLiter,
@JsonProperty("HPA")
HectoPascal,
@JsonProperty("HZ")
HertzPerSecond,
@JsonProperty("KG")
Kilogram,
@JsonProperty("M3")
CubicMeter,
@JsonProperty("1")
OneCIS,
@JsonProperty("PAL")
Pallet,
@JsonProperty("PC")
Piece,
@JsonProperty("PRS")
NumberOfPersons,
@JsonProperty("PS")
PicoSecond,
@JsonProperty("PT")
PintUSLiquid,
@JsonProperty("PU")
PERFORMANCEUNIT,
@JsonProperty("QT")
QuartUSLiquid,
@JsonProperty("RHO")
GramPerCubicCentimeter,
@JsonProperty("ROL")
Role,
@JsonProperty("S")
Second,
@JsonProperty("SET")
SET,
@JsonProperty("SH")
Sheet,
@JsonProperty("ST")
Items,
@JsonProperty("SY")
System,
@JsonProperty("TC3")
OnePerCubicCentimeter,
@JsonProperty("TES")
Tesla,
@JsonProperty("TG")
TenGram,
@JsonProperty("TM3")
OnePerCubicMeter,
@JsonProperty("TNK")
TANK,
@JsonProperty("TO")
Tonne,
@JsonProperty("TON")
USton,
@JsonProperty("TR")
Troyounce,
@JsonProperty("UN")
UniDade,
@JsonProperty("V")
Volt,
@JsonProperty("V%")
PercentVolume,
@JsonProperty("V%O")
PermilleVolume,
@JsonProperty("VAL")
ValueOnlyMaterial,
@JsonProperty("VPB")
VolumePartsPerBillion,
@JsonProperty("VPM")
VolumePartsPerMillion,
@JsonProperty("VPT")
VolumePartsPerTrillion,
@JsonProperty("W")
Watt,
@JsonProperty("WMK")
HeatConductivity,
@JsonProperty("YD")
Yards,
@JsonProperty("YD2")
SquareYard,
@JsonProperty("YD3")
CubicYard,
@JsonProperty("Z01")
APerus,
@JsonProperty("Z02")
A2S,
@JsonProperty("Z03")
CPerW,
@JsonProperty("Z04")
CdPermSquare,
@JsonProperty("Z05")
CH,
@JsonProperty("Z06")
COULOMB,
@JsonProperty("Z07")
Cyc,
@JsonProperty("Z08")
DECIBEL,
@JsonProperty("Z09")
DECIBELRELToCARRIERWA,
@JsonProperty("Z10")
DECIRELToCARRIERWAPerHZ,
@JsonProperty("Z11")
Gcm,
@JsonProperty("Z12")
Gauss,
@JsonProperty("Z13")
Gf,
@JsonProperty("Z14")
Lm,
@JsonProperty("Z15")
LUX,
@JsonProperty("Z16")
mAH,
@JsonProperty("Z17")
MB,
@JsonProperty("Z18")
MEGABITPerSECOND,
@JsonProperty("Z19")
MGOe,
@JsonProperty("Z20")
MilliHENRY,
@JsonProperty("Z21")
MilliOHM,
@JsonProperty("Z22")
MILLISIEMENS,
@JsonProperty("Z23")
MILLIWATPerMilliVOLT,
@JsonProperty("Z24")
mmH20,
@JsonProperty("Z25")
MuPerCmSquare,
@JsonProperty("Z26")
mVPerA,
@JsonProperty("Z27")
mWPerC,
@JsonProperty("Z28")
Oe,
@JsonProperty("Z29")
ohmPerKm,
@JsonProperty("Z30")
P,
@JsonProperty("Z31")
PCS,
@JsonProperty("Z32")
pFPerV,
@JsonProperty("Z33")
PwrLVLRELToOneMilliW,
@JsonProperty("Z34")
ppc,
@JsonProperty("Z35")
ppmPerC,
@JsonProperty("Z36")
uAPerV,
@JsonProperty("Z37")
USEDWithMEMORIES,
@JsonProperty("Z38")
VPerA,
@JsonProperty("Z39")
Vac,
@JsonProperty("Z40")
Vdc,
@JsonProperty("Z41")
VOLT_ROOT_MEAN_SQUARE,
@JsonProperty("Z42")
Vpp,
@JsonProperty("Z43")
KbPerS,
@JsonProperty("Z44")
kvac,
@JsonProperty("Z45")
ppmPerCE,
@JsonProperty("Z46")
uS,
@JsonProperty("Z47")
mInCubePerMi,
@JsonProperty("Z48")
rpm,
@JsonProperty("Z49")
VPeruS,
@JsonProperty("Z50")
dot,
@JsonProperty("Z51")
Er,
@JsonProperty("Z52")
uA,
@JsonProperty("Z53")
uF,
@JsonProperty("Z61")
AMOUNT,
@JsonProperty("Z62")
KiloPC,
@JsonProperty("Z63")
GramPerCubicMeter,
@JsonProperty("Z64")
COULOMB_ELECTRIC_CHARGE,
@JsonProperty("Z65")
Truck1Ton,
@JsonProperty("Z66")
Truck2WithHalfTons,
@JsonProperty("Z67")
Truck5Tons,
@JsonProperty("Z68")
Truck8Tons,
@JsonProperty("Z69")
Truck11Tons,
@JsonProperty("Z70")
ManMonth,
@JsonProperty("10")
Days,
@JsonProperty("2M")
CentimeterPerSecond,
@JsonProperty("2X")
MeterPerMinute,
@JsonProperty("4G")
MicroLiter,
@JsonProperty("4O")
MicroFarad,
@JsonProperty("4T")
PicoFarad,
@JsonProperty("A87")
Gigaohm,
@JsonProperty("A93")
GramPerCubicMeterAdd,
@JsonProperty("B34")
KilogramPerCubicDecimeter,
@JsonProperty("B45")
KiloMol,
@JsonProperty("B47")
KiloNewton,
@JsonProperty("B73")
Meganewton,
@JsonProperty("B75")
MegaHM,
@JsonProperty("B78")
MegaVolt,
@JsonProperty("B84")
MicroAmpere,
@JsonProperty("C10")
MilliFarad,
@JsonProperty("C36")
MolPerCubicMeter,
@JsonProperty("C38")
MolPerLiter,
@JsonProperty("C39")
NanoAmpere,
@JsonProperty("C41")
NanoFarad,
@JsonProperty("C56")
NewtonPerSquareMillimeter,
@JsonProperty("CDM")
CubicDecimeter,
@JsonProperty("CS")
Case,
@JsonProperty("CTL")
Centiliter,
@JsonProperty("D10")
SiemensPerMeter,
@JsonProperty("D41")
TonPerCubicMeter,
@JsonProperty("D46")
VoltAmpere,
@JsonProperty("DPR")
cProjectsUnitFReqCapacity,
@JsonProperty("EE")
EnzymeUnits,
@JsonProperty("FA")
Fahrenheit,
@JsonProperty("GB")
Gigabyte,
@JsonProperty("GC")
DegreesCelsius,
@JsonProperty("GLL")
USGallon,
@JsonProperty("GLM")
GallonsPerMile,
@JsonProperty("GQ")
MicroGramPerCubicMeter,
@JsonProperty("GW")
GramactIngrd,
@JsonProperty("HAR")
Hectare,
@JsonProperty("IN")
SquareInch,
@JsonProperty("IN3")
CubicInch,
@JsonProperty("STD")
Hours,
@JsonProperty("TAG")
DaysAdd,
@JsonProperty("TH")
ThousandsAdd,
@JsonProperty("UGL")
MicroGramPerLiter,
@JsonProperty("TST")
Test,
@JsonProperty("V01")
MicroSiemensPerCentimeter,
@JsonProperty("V02")
MilliMolPerLiter,
@JsonProperty("WCH")
Weeks,
@JsonProperty("WTL")
EvaporationRate,
@JsonProperty("Z71")
SVCCommonNet,
@JsonProperty("Z72")
SVCKoreaGross,
@JsonProperty("Z73")
SVCEuropeGross,
@JsonProperty("Z74")
REAByte,
@JsonProperty("Z75")
REAKilobyte,
@JsonProperty("Z76")
REAMegabyte,
@JsonProperty("Z77")
REAGigabyte

}
